In [104]:
import numpy as np
from scipy.linalg import lu_factor, lu_solve


In [185]:
def jacobi(A, b, x0, nit):    
    """ Método de Jacobi para solução do sistema Ax=b.

    x = jacobi(A, b, x0, nit)

    Entradas:
        - A: matriz n x n (tipo: lista de listas)
        - b: vetor n x 1 (tipo: lista)
        - x0: vetor n x 1, ponto de partida (tipo: lista)
        - nit: número de iterações
    
    Saídas:
        - x:  matriz n x nit, contendo a sequência de vetores
        - c:  norma da matriz de iteração
    """ 
    
    import numpy as np    

    f = lambda obj: isinstance(obj,list)     
    if not all([f(A),f(b),f(x0)]):
        raise TypeError('A, b e x0 devem ser do tipo list.')
    else:
        A = np.asarray(A)
        b = np.asarray(b)
        x0 = np.asarray(x0)
            
    n = np.size(b)
    x = np.zeros((n, nit),dtype=float)
    x[:,0] = x0
        
    P = np.diag(np.diag(A))
    Q = P - A # elementos de fora da diagonal
    C = np.linalg.solve(P,Q) # matriz da função de iteração
    g = np.linalg.solve(P,b) # vetor da função de iteração
    c = np.linalg.norm(C) 
    
    #processo iterativo
    X = x0[:]    
    j = 1
    for j in range(1,nit):        
        X = C.dot(X) + g        
        x[:,j] = X
               
    return x, c

In [175]:
def gauss_seidel(A, b, x0, nit, tol):
    """ Método de Gauss-Seidel de solucao do sistema Ax=b

    Entradas:
        - A: matriz n x n (tipo: lista de listas)
        - b: vetor n x 1 (tipo: lista)
        - x0: vetor n x 1, ponto de partida (tipo: lista)
        - nit: número de iterações
        - tol: tolerancia de erro relativo
   
    Saídas:
        - x: matriz n x N, contendo a sequência de vetores
        - c: norma da matriz de iteração       
        - err: erro relativo percentual por iteracao (norma 2)
    """

    import numpy as np
    n = len(b)
    x = np.zeros((n, nit))
    x[:,0] = x0
    xx = x0 # iterada atual
    P = np.tril(A)
    N = P - A
    C = np.linalg.solve(P, N)
    c = np.linalg.norm(C)
    g = np.linalg.solve(P, b)

    for j in range(1, nit):
        xx = C @ xx + g
        x[:,j] = xx
         
    key = True    
        
    for i in range(1, nit):   
             
        e = np.linalg.norm(x[:,i] - x[:,i-1])/np.linalg.norm(x[:,i])
            
        if (e < tol) and (key == True):                        
            key = False

    return x, c


In [197]:
# FusionCells, SolarCaps, Geothermal, Battery
B = [[70,  8, 10,  1,  5], # Shield (Escudos)
     [ 5, 50,  6,  2,  4], # Defence (Defesa / EM & tratores)
     [12,  3, 65,  2,  7], # Fighter (Esquadrões)
     [ 6,  4, 10, 40,  3], # IonCannon (Canhões de Íons)
     [15,  5,  8,  4, 55]] # Engines (Propulsão)

b = [7370,
     1670,
     1815,
     1220,
     3330]

In [187]:
# Consideraremos que as matrizes triangulares inferiores sempre terão a sua diagonal principal formada por entradas iguais a 1.
# L (triangular inferior) e U (triangular superior)
# piv: o vetor de pivoteamento
lu, piv = lu_factor(B) # Fatoração LU
x_lu = lu_solve((lu, piv), b) #Ex = d
res_lu = np.linalg.norm(B @ x_lu - b) # Calcula o resíduo do sistema: r = Ex−d

In [188]:
x_lu

array([100.,  20.,   5.,  10.,  30.])

In [193]:
x0 = [1, 1, 1, 1, 1]
x_jacobi, norma_j = jacobi(B, b, x0, 150)

In [194]:
x_gs, norma_gs = gauss_seidel(B, b, x0, 150, 1e-10)

In [195]:
x_jacobi[:, -1]

array([100.,  20.,   5.,  10.,  30.])

In [196]:
x_gs[:, -1]

array([100.,  20.,   5.,  10.,  30.])